# Generated by Django 6.0.6 on 2026-06-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['expires_at'], name='payments_id_expires_691ca7_idx'),
        ),
    ]
